meta_product_name: Daphné Visuals
meta_title: Daphné Visuals – Portfolio
meta_description: Hey ! Je suis une développeuse full-stack, UI/UX designer, et une photographe passionée basée en Suisse.
# meta_image: “cover.png” # should exist in `app/assets/images/`
